Teet 185 be check expired booking
TeethCareProject/teethcare-backend pull request #63
Opened 2022-07-09 13:34 UTC by tuongdii

2022-07-09 13:45 UTC, NTH260202 requested changes

2022-07-09 13:45 UTC, NTH260202 commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:sqlserver://localhost:1433;database=TEETHCARE;encrypt=true;trustServerCertificate=true
them cai sendTimeAsDatetime=false nha :v

2022-07-09 13:48 UTC, NTH260202 approved these changes

2022-07-10 15:25 UTC, ZERO-94 approved these changes

2022-07-10 15:35 UTC, merged