hot_fix_get_all_clinic_staff
TeethCareProject/teethcare-backend pull request #67
Opened 2022-07-10 15:56 UTC by tuongdii

2022-07-10 16:21 UTC, NTH260202 approved these changes

2022-07-11 08:18 UTC, ZERO-94 requested changes

2022-07-11 08:18 UTC, ZERO-94 commented on src/main/java/com/teethcare/service/impl/account/DentistServiceImpl.java
> +         return dentistRepository.findByClinicIdAndStatus(theId, status);
the id what ?

2022-07-11 08:46 UTC, ZERO-94 approved these changes

2022-07-11 08:46 UTC, merged